name: Generate Sitemap

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Generate Sitemap
        run: |
          python generate_sitemap.py
          
      - name: Commit and Push Sitemap
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add sitemap.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate sitemap" && git push) 